name: space_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2
dependencies:
  flutter_3d_controller: ^2.3.0
  flutter_bounceable: ^1.2.0
  flutter_gen: ^5.14.1
  build_runner: ^2.12.0
  flutter_svg: ^2.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images3D/
    - assets/data/planets.json

  fonts:
    - family: Space Grotesk
      fonts:
        - asset: assets\fonts/SpaceGrotesk-Regular.ttf
        - asset: assets\fonts/SpaceGrotesk-Medium.ttf
        - asset: assets\fonts/SpaceGrotesk-SemiBold.ttf
        - asset: assets\fonts/SpaceGrotesk-Bold.ttf


flutter_gen:
  output: lib/core/gen/
  integrations:
    image: true
    flutter_svg: true